version: "3.7"

services:
  app:
    ports:
      - "80:80"
    build: ./docker/app
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: laravel_db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      TZ: "Asia/Tokyo"

    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/db/data:/var/www/mysql
      - ./docker/db/my.conf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
